<?php
declare(strict_types=1);

return [
    'classes' => [
        'table' => 'classes',
        'primary_key' => 'id',
        'title' => 'name',
        'fields' => [
            // ── Core display fields ──────────────────────────────────
            'name'                  => ['label' => 'Class Name',           'type' => 'text',     'required' => true],
            'category'              => ['label' => 'Category',             'type' => 'text',     'required' => false],
            'location'              => ['label' => 'Location',             'type' => 'text',     'required' => false],
            'badge_label'           => ['label' => 'Badge Label',          'type' => 'text',     'required' => false],
            'registration_required' => ['label' => 'Registration Required','type' => 'number',   'required' => false],
            'description'           => ['label' => 'Description',          'type' => 'textarea', 'required' => false],
            'highlights'            => ['label' => 'Highlights',           'type' => 'textarea', 'required' => false],
            'video_url'             => ['label' => 'Video URL',            'type' => 'text',     'required' => false],
            'upcoming_batches'      => ['label' => 'Upcoming Batches',     'type' => 'textarea', 'required' => false],
            'schedule'              => ['label' => 'Schedule',             'type' => 'textarea', 'required' => false],
            'age_requirement'       => ['label' => 'Age Requirement',      'type' => 'text',     'required' => false],
            'special_instruction'   => ['label' => 'Special Instruction',  'type' => 'text',     'required' => false],
            'price_note'            => ['label' => 'Price Note',           'type' => 'text',     'required' => false],
            'price'                 => ['label' => 'Base Price',           'type' => 'number',   'required' => false],
            'instructor'            => ['label' => 'Instructor',           'type' => 'text',     'required' => false],
            'image_path'            => ['label' => 'Image',                'type' => 'file',     'required' => false],
            // ── Booking settings ─────────────────────────────────────
            'booking_enabled'       => ['label' => 'Enable Booking',       'type' => 'number',   'required' => false],
            'booking_type'          => ['label' => 'Booking Type',         'type' => 'text',     'required' => false],
            'slot_capacity'         => ['label' => 'Max Capacity',         'type' => 'number',   'required' => false],
            'timeslots'             => ['label' => 'Time Slots',           'type' => 'text',     'required' => false],
            'tiers'                 => ['label' => 'Program Tiers',        'type' => 'text',     'required' => false],
        ],
    ],
    'events' => [
        'table' => 'events',
        'primary_key' => 'id',
        'title' => 'title',
        'fields' => [
            'title' => ['label' => 'Event Title', 'type' => 'text', 'required' => true],
            'delivery_mode' => ['label' => 'Delivery Mode', 'type' => 'text', 'required' => false],
            'event_date' => ['label' => 'Event Date', 'type' => 'date', 'required' => true],
            'event_time' => ['label' => 'Event Time', 'type' => 'time', 'required' => false],
            'end_date' => ['label' => 'End Date', 'type' => 'date', 'required' => false],
            'end_time' => ['label' => 'End Time', 'type' => 'time', 'required' => false],
            'location' => ['label' => 'Location', 'type' => 'text', 'required' => false],
            'ticket_price' => ['label' => 'Ticket Price', 'type' => 'number', 'required' => false],
            'total_seats' => ['label' => 'Total Seats', 'type' => 'number', 'required' => false],
            'available_seats' => ['label' => 'Available Seats', 'type' => 'number', 'required' => false],
            'description' => ['label' => 'Description', 'type' => 'textarea', 'required' => false],
            'highlights' => ['label' => 'Highlights', 'type' => 'textarea', 'required' => false],
            'image_path' => ['label' => 'Image', 'type' => 'file', 'required' => false],
            'gallery_image_1' => ['label' => 'Gallery Image 1', 'type' => 'file', 'required' => false],
            'gallery_image_2' => ['label' => 'Gallery Image 2', 'type' => 'file', 'required' => false],
            'gallery_image_3' => ['label' => 'Gallery Image 3', 'type' => 'file', 'required' => false],
            'testimonial_1_name' => ['label' => 'Testimonial 1 Name', 'type' => 'text', 'required' => false],
            'testimonial_1_text' => ['label' => 'Testimonial 1 Text', 'type' => 'textarea', 'required' => false],
            'testimonial_2_name' => ['label' => 'Testimonial 2 Name', 'type' => 'text', 'required' => false],
            'testimonial_2_text' => ['label' => 'Testimonial 2 Text', 'type' => 'textarea', 'required' => false],
            'testimonial_3_name' => ['label' => 'Testimonial 3 Name', 'type' => 'text', 'required' => false],
            'testimonial_3_text' => ['label' => 'Testimonial 3 Text', 'type' => 'textarea', 'required' => false],
        ],
    ],
    'gallery' => [
        'table' => 'gallery',
        'primary_key' => 'id',
        'title' => 'title',
        'fields' => [
            'title' => ['label' => 'Title', 'type' => 'text', 'required' => true],
            'category' => ['label' => 'Category', 'type' => 'text', 'required' => false],
            'description' => ['label' => 'Description', 'type' => 'textarea', 'required' => false],
            'image_path' => ['label' => 'Image', 'type' => 'file', 'required' => false],
            'video_path' => ['label' => 'Video', 'type' => 'file', 'required' => false],
        ],
    ],
    'blogs' => [
        'table' => 'blogs',
        'primary_key' => 'id',
        'title' => 'title',
        'fields' => [
            'title' => ['label' => 'Blog Title', 'type' => 'text', 'required' => true],
            'author' => ['label' => 'Author Name', 'type' => 'text', 'required' => true],
            'publish_date' => ['label' => 'Publish Date', 'type' => 'date', 'required' => true],
            'content' => ['label' => 'Content', 'type' => 'textarea', 'required' => true],
            'image_path' => ['label' => 'Thumbnail Image', 'type' => 'file', 'required' => false],
        ],
    ],
    'bookings' => [
        'table' => 'bookings',
        'primary_key' => 'id',
        'title' => 'customer_name',
        'fields' => [
            'class_id' => ['label' => 'Class ID', 'type' => 'number', 'required' => true],
            'customer_name' => ['label' => 'Customer Name', 'type' => 'text', 'required' => true],
            'customer_email' => ['label' => 'Customer Email', 'type' => 'text', 'required' => true],
            'customer_phone' => ['label' => 'Customer Phone', 'type' => 'text', 'required' => false],
            'program_tier' => ['label' => 'Program Tier', 'type' => 'text', 'required' => false],
            'booking_date' => ['label' => 'Booking Date', 'type' => 'date', 'required' => true],
            'time_slot' => ['label' => 'Time Slot', 'type' => 'text', 'required' => true],
            'quantity' => ['label' => 'Quantity', 'type' => 'number', 'required' => true],
            'personal_or_group' => ['label' => 'Type', 'type' => 'text', 'required' => false],
            'payment_status' => ['label' => 'Payment Status', 'type' => 'text', 'required' => false],
            'transaction_id' => ['label' => 'Transaction ID', 'type' => 'text', 'required' => false],
        ],
    ],
    'enquiries' => [
        'table' => 'enquiries',
        'primary_key' => 'id',
        'title' => 'subject',
        'fields' => [
            'name' => ['label' => 'Name', 'type' => 'text', 'required' => true],
            'email' => ['label' => 'Email', 'type' => 'text', 'required' => false],
            'phone' => ['label' => 'Phone', 'type' => 'text', 'required' => false],
            'subject' => ['label' => 'Subject', 'type' => 'text', 'required' => true],
            'message' => ['label' => 'Message', 'type' => 'textarea', 'required' => true],
            'status' => ['label' => 'Status', 'type' => 'text', 'required' => false],
            'created_at' => ['label' => 'Created At', 'type' => 'text', 'required' => false],
        ],
    ],
];
